### ISSUE TITLE
Add a typeform link to the join us button in the navbar.

### ISSUE THREAD

**Issue by kumarshantanu01** [Webwiznitr/webwiz-portfolio#1]
In the Typeform add all the required questions.

**Comment by samrath-sudesh-acharya** [comment]
@kumarshantanu01  can you assign me this

**Comment by samrath-sudesh-acharya** [comment]
and can please give more details on what all questions to be asked other than the basic details

**Comment by kumarshantanu01** [comment]
yes @samrath-sudesh-acharya do it.
Questions:
1. Name
2. Email
3. Phone No.
4. Roll No. 
5. Branch
6. Link to join whatsapp group (do not attach link now, will do that later)

**Comment by samrath-sudesh-acharya** [comment]
ok on it @kumarshantanu01
