### ISSUE TITLE
Hover effect on projects cards 

### ISSUE THREAD

**Issue by kumarshantanu01** [Webwiznitr/webwiz-portfolio#22]
Hover effect on projects cards on home page.

**Comment by rkoleci** [comment]
can you assign this to me ?

**Comment by kumarshantanu01** [comment]
Sure @rkoleci .

**Comment by kumarshantanu01** [comment]
For your reference,
you have to style this section
![Webwiz - Google Chrome 10_12_2021 22_13_09 (2)](https://user-images.githubusercontent.com/76111005/145610455-17cda2d1-cd1e-45c5-ac0c-9cbb1db59476.png)

**Comment by rkoleci** [comment]
Check it
