### ISSUE TITLE
Divide the Team page into 3 sections.

### ISSUE THREAD

**Issue by kumarshantanu01** [Webwiznitr/webwiz-portfolio#3]
Divide the Team page into 3 sections with these topics- 
1. Executive Body 2021-22 (all current postholders, total 6 people so put 3 in 1 row)
2. Founding Members (ex-postholders, 3 people in 1 row)
3. Team (rest of the members as it is, 4 in 1 row)

**Comment by prkhrsrvstv1** [comment]
Hey @kumarshantanu01, I can take this up. Feel free to assign this issue to me.

**Comment by kumarshantanu01** [comment]
Sure @prkhrsrvstv1
