### ISSUE TITLE
Enhancement: Add these projects

### ISSUE THREAD

**Issue by kumarshantanu01** [Webwiznitr/webwiz-portfolio#4]
Add these projects in the cards where daffodil is written on the Home page. Add a relevant image and one-line content to it.

1. Daffodil (https://github.com/Webwiznitr/Project-daffodil)
2. Clubopedia (https://github.com/Webwiznitr/Project-keppel)
3. Webdev Roadmap (https://webwiz.notion.site/webwiz/Road-map-to-became-Web-Beast-Webwiz-7b0334c890c7482a9738687b757a92da)

**Comment by akash5100** [comment]
I would like to claim this issue, please guide me.

**Comment by akash5100** [comment]
please provide me images you want to display in cards and that "one-line content" also assign this issue to me.

**Comment by kumarshantanu01** [comment]
sure @akash5100, go for it.

content:
Daffodil - Course material for 1st year engineering students in IIT/NITs.
Clubopedia - Clubopedia ~ an encyclopedia of clubs of NITR.
Webdev Roadmap - Road-map to become Web Beast.

For images you can leave it the same as before or add any relevant image if you find it.
And code has been repeated for each card, so reduce the code.

**Comment by akash5100** [comment]
Please guide me from where should I start.

**Comment by kumarshantanu01** [comment]
You can find the cards in src/components/card.
The files are "Pcard and Projectcard" in these files you can make changes.

**Comment by vijaykrishna536** [comment]
Hi @kumarshantanu01 
Would like to work on this issue, If no one is working on the same
Thank you
