### ISSUE TITLE
Change the design of the About us page.

### ISSUE THREAD

**Issue by kumarshantanu01** [Webwiznitr/webwiz-portfolio#7]
You can change the design of about us page according to you and which looks good. You can also try by making cards and divide the same content into cards.
You can take reference from about us section from here (https://in.pinterest.com/pin/415738609355792449/)

**Comment by vipul-rajput** [comment]
Hey, @kumarshantanu01, Can please assign this issue to me.

**Comment by kumarshantanu01** [comment]
sure @vipul-rajput go for it.

**Comment by vipul-rajput** [comment]
Hey,will it be okay if I use normal css instead of styled component.

**Comment by kumarshantanu01** [comment]
Ok, you can use it but don't remove the previous codes, just comment out the earlier part.

**Comment by Emiliano-Russo** [comment]
maybe @vipul-rajput forgot this task, i'll do it

**Comment by oneamanish** [comment]
see my pull req.
