### ISSUE TITLE
Modify the events card on home page

### ISSUE THREAD

**Issue by kumarshantanu01** [Webwiznitr/webwiz-portfolio#8]
The event card on the home page needs to be modified.
Take this as reference (https://www.figma.com/file/vJVpL9yT8w59GfhnBQslmB/WEBWIZ-PORTFOLIO?node-id=0%3A1)

**Comment by ghousahmed** [comment]
Can you assign it to me?

**Comment by kumarshantanu01** [comment]
sure @ghousahmed
